### ISSUE TITLE
Suggession: Change title color

### ISSUE THREAD

**Issue by congtuan010418** [congtuan200918/github-crash-course#2]
I think it looks better if the main title is a bit more orange.

The styling rule could be changed like this:

```css
h1 {
  color: #e8d4b2;
}
```
